#!/bin/bash
set -euo pipefail

while true; do
  HEADERS="$(mktemp)"
  # Get an event from the Lambda RIE
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://localhost:9001/2018-06-01/runtime/invocation/next")
  echo "Event data: $EVENT_DATA"

  INVOCATION_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Call your handler function with the event data and context as arguments
  RESPONSE=$(/usr/local/bin/julia -e "include(\"/app/lambda_handler.jl\"); response = handler(\"$EVENT_DATA\", nothing); print(response)")

  # Post the response back to the Lambda RIE
  curl -X POST "http://localhost:9001/2018-06-01/runtime/invocation/$INVOCATION_ID/response" -d "$RESPONSE"
done
